[package]
name = "rust_filter"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
